package com.strutoocustomer.customer.models

import com.google.gson.annotations.SerializedName
import com.strutoocustomer.customer.recycleradapter.AbstractModel

data class UserModel(
    val __v: Int? = null,
    val _id: String? = null,
    val accessToken: String? = null,
    val amount: Int? = null,
    val appleId: String? = null,
    val isOnline: Boolean? = false,
    val floristNo: String? = null,
    val birthDate: String? = null,
    val city: String? = null,
    val lat: Double? = null,
    val lng: Double? = null,
    val age: String? = null,
    val country: String? = null,
    val stripeConnectId: String? = null,
    val isStripeConnectCompleted: String? = null,
    val countryCode: String? = null,
    val createdAt: String? = null,
    val description: String? = null,
    val deviceToken: String? = null,
    val deviceType: String? = null,
    val email: String? = null,
    val facebookId: String? = null,
    var image: String? = null,
    var firstName: String? = null,
    val fullName: String? = null,
    val gender: String? = null,
    val geoFence: List<String> = emptyList(),
    val googleId: String? = null,
    val id: String? = null,
    val isActive: Boolean? = false,
    val isApproved: Boolean? = false,
    val isBankDetailsUpdated: Boolean? = false,
    val driverId: String? = "",
    val isBlocked: Boolean? = false,
    val isDeleted: Boolean? = false,
    val isDrivingLicenseUpdated: Boolean? = false,
    val isEmailVerified: Boolean? = false,
    val isIdentified: Boolean? = false,
    val isNotification: Boolean? = false,
    val isPhoneVerified: Boolean? = false,
    val isProfileSetup: Boolean? = false,
    val isResetPassword: Boolean? = false,
    val isSocialLogin: Int? = null,
    val isSubscribed: String? = null,
    val isVehicleDetailsUpdated: Boolean? = false,
    val isVerified: Boolean? = false,
    val isdriverOnline: Boolean? = false,
    val jti: String? = null,
    var lastName: String? = null,
    val loginCount: Int? = null,
    val nationality: String? = null,
    val password: String? = null,
    val phone: String? = null,
    val points: Int? = null,
    val profilePic: String? = null,
    val role: String? = null,
    val secondaryPhone: String? = null,
    val secondaryPhoneCountryCode: String? = null,
    val countryNameCode: String? = null,
    val stateCode: String? = null,
    val secretCode: String? = null,
    val secretExpiry: String? = null,
    val socialId: String? = null,
    val socialType: String? = null,
    val state: String? = null,
    @SerializedName("address") val address: String? = null,
    val type: String? = null,
    val updatedAt: String? = null,
    val userId: String? = null,
    val userName: String? = null,
    val verificationBy: String? = null
) : AbstractModel()
